#!/bin/bash
# We are currently using pipenv version: 2020.8.13
# Latest version at time of writing: 2020.11.4

set -e

# TEST_PIPENV_VERSION=2020.8.13
TEST_PIPENV_VERSION=2020.11.4

echo "Running repro against pipenv version: ${TEST_PIPENV_VERSION}"

docker build --build-arg TEST_PIPENV_VERSION=$TEST_PIPENV_VERSION -t pipenv-graph-bug .

echo "About to run docker run... it can take a minute before output appears.. just hang on!"

docker run --rm pipenv-graph-bug
